### ISSUE TITLE
Troom spikes when using MQTT as temperature source

### ISSUE THREAD

**Issue by tomm1ed** [absalom-muc/MHI-AC-Ctrl#105]
I am using an external Temperature sensor to set the Troom value on my SRC35ZSX but I see weird spikes when heating in the value, it kinda looks like the internal sensor also keeps updating (near the Airco of course it is hotter than at the temp sensor which is on the other end of the room)

See https://tweakers.net/fotoalbum/image/ax3hBggwaNhKPqMj9ZOg04s7.jpg for the temperature the Airco is reporting in the MQTT topic and https://tweakers.net/fotoalbum/image/CPcGYRJTto0jOrhyxENbRJuf.jpg for the actual temperature measurement.
The value of Troom is updated every minute from the ESP (running Tasmota) through MQTT

**Comment by Blokkert** [comment]
Same issue here.

see: https://tweakers.net/fotoalbum/image/W3rlt7D76CKyctGQlkOCe448.png
both values in one graph.

its worst on the moment the unit is in heating mode, spikes continously.
Tried different things in the mqtt.publish, but problems stays everytime.

Current code:

```
 # Airco

- id: Tuya Room Temp To AC-Living
  alias: Tuya Room Temp To AC-Living
  trigger:
  - platform: time_pattern
    minutes: /1
#  - platform: state
#    entity_id:
#      - sensor.temptuya1_temperature
  condition:
  - condition: template
    value_template: "{{ states('sensor.temptuya1_temperature')|is_number }}"
  action:
  - service: mqtt.publish
    data:
      topic: AC_MHI_Living/Troom
      payload_template: "{{ states('sensor.temptuya1_temperature') }}"
  mode: single
```

tried this to, no difference.

`payload_template: '{{ states.sensor.temptuya1_temperature.state }}'`

**Comment by tomm1ed** [comment]
My setup uses Tasmota with the following rules:
```
rule1 ON BMP280#Temperature DO Var1 %value% ENDON
rule2 ON Time#Minute|1 DO publish MHI-AC-Ctrl-Livingroom/Troom %Var1% endon
rule1 1
rule2 1
```

**Comment by tomm1ed** [comment]
Created a graph with both values superimposed (never knew this was possible, thanks @Blokkert ;) )
 
![](https://tweakers.net/fotoalbum/image/IDZTWGH9QqtekPzhBe8ze9eV.png)

**Comment by absalom-muc** [comment]
Can you provide a log file? Maybe something happens in between.

**Comment by tomm1ed** [comment]
> Can you provide a log file? Maybe something happens in between.

A log file of what exactly?

**Comment by absalom-muc** [comment]
The log of the serial interface to see what happens between 2 spikes.

**Comment by tomm1ed** [comment]
> The log of the serial interface to see what happens between 2 spikes.

Okay, excuse for being a bit daft but how can I access this log?

**Comment by Blokkert** [comment]
i did check something reqarding mqtt timeout, its configured on 20 sec. So i changed the mqtt.publish to every 10 seconds, issue stays te same.

**Comment by absalom-muc** [comment]
> > The log of the serial interface to see what happens between 2 spikes.
> 
> Okay, excuse me for being a bit daft but how can I access this log?

If you used the Arduino IDE for programming the MHI-AC-Ctrl board, you can use the serial monitor of the Arduino IDE for displaying the log output. Please copy the log to a text file.

**Comment by absalom-muc** [comment]
> i did check something reqarding mqtt timeout, its configured on 20 sec. So i changed the mqtt.publish to every 10 seconds, issue stays te same.

When you mention the mqtt.publish, I assume you mean the publish from your external temperature sensor - correct?

**Comment by PietNL** [comment]
As I'm also using this feature (also with HA) and not seeing these spikes, I just compared my automation with yours and noticed that you are using this:

```action:
  - service: mqtt.publish
    data:
      topic: AC_MHI_Living/Troom
      payload_template: "{{ states('sensor.temptuya1_temperature') }}"
```


And I'm posting the temp sensor to a different topic(including the set):

```
action:
  - service: mqtt.publish
    data:
      topic: AC-Living/set/Troom
      payload_template: "{{ states('sensor.living_temperature') }}"
```

If you try this, does that make a difference?
