### ISSUE TITLE
Home Assistant Enhancement Idea

### ISSUE THREAD

**Issue by Daryn-L** [absalom-muc/MHI-AC-Ctrl#29]
I use home assistant for this.

My HA config is:

```
climate heatpump:
  - platform: mqtt
    unique_id: mhi0001a
    name: HeatPump
    initial: 22
    min_temp: 18
    max_temp: 30
    modes:
      - "auto"
      - "dry"
      - "cool"
      - "fan_only"
      - "heat"
      - "off"
    swing_modes:
      - "1"
      - "2"
      - "3"
      - "4"
      - "Swing"
    fan_modes:
      - "1"
      - "2"
      - "3"
      - "4"
    mode_command_topic: "MHI-AC-Ctrl/set/Mode"
    temperature_command_topic: "MHI-AC-Ctrl/set/Tsetpoint"
    fan_mode_command_topic: "MHI-AC-Ctrl/set/Fan"
    swing_mode_command_topic: "MHI-AC-Ctrl/set/Vanes"
    current_temperature_topic: "MHI-AC-Ctrl/Troom"
    mode_state_topic: "MHI-AC-Ctrl/Mode"
    temperature_state_topic: "MHI-AC-Ctrl/Tsetpoint"
    fan_mode_state_topic: "MHI-AC-Ctrl/Fan"
    swing_mode_state_topic: "MHI-AC-Ctrl/Vanes"

```

Home assistant will only accept certain topic commands which can't be changed easily e.g. "MHI-AC-Ctrl/set/Mode" -> "fan_only"

My suggestion is to have something like follows:

```
//Platform
#define USE_HOME_ASSISTANT true

#define PAYLOAD_MODE_AUTO HOME_ASSISTANT == true  ? "auto" : "Auto"
#define PAYLOAD_MODE_STOP HOME_ASSISTANT == true  ? "stop" : "Stop"
#define PAYLOAD_MODE_DRY HOME_ASSISTANT == true  ? "dry" : "Dry"
#define PAYLOAD_MODE_COOL HOME_ASSISTANT == true  ? "cool" : "Cool"
#define PAYLOAD_MODE_FAN HOME_ASSISTANT == true  ? "fan_only" : "Fan"
#define PAYLOAD_MODE_HEAT HOME_ASSISTANT == true  ? "heat" : "Heat"
#define PAYLOAD_OP_DEFROST_ON HOME_ASSISTANT == true  ? "on" : "On"
#define PAYLOAD_OP_DEFROST_OFF HOME_ASSISTANT == true  ? "off" : "Off"
```

The only problem I am getting is in the line
`
#define PAYLOAD_MODE_FAN HOME_ASSISTANT == true  ? "fan_only" : "Fan"
`

Not sure what it is as I do not know C.  If it was in Java I could probably figure it out.

Anyways, I think it would be a nice addition to have this work 'out of the box' with HA.
